backend:
  name: git-gateway
  repo: barnettjoe/coleandlopez

media_folder: static/assets
public_folder: assets

collections:
  - name: section
    label: Section
    folder: sections
    create: true
    fields:
      - { name: title, label: Title }
      - { name: bannerImage, label: Banner Image, widget: image }
      - { name: body, label: Body, widget: markdown }
