backend:
  name: git-gateway
  repo: barnettjoe/coleandlopezspotify

media_folder: static/assets
public_folder: assets

collections:
  - name: section
    label: Section
    folder: sections
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }